#include "tactic.h"
#include"ctp_order_manager.h"
#include<iostream>
using namespace std;

void tactic::init()
{
    ordersize=0;
    lasttradeprice=0;
}
void tactic::set_ctp_order_manager(ctp_order_manager * p)
{
    om=p;
}
void tactic::quote(const std::string & symbol, const std::string & ba, long level, double price, long quotesize)
{
//    cerr <<"now ordersize\t"<<ordersize<< "\tnow price\t " <<price << "\tlast trade price\t" << lasttradeprice <<endl;
    if(symbol=="IF1412")
    {
        if(lasttradeprice==0)
        {
            lasttradeprice=price;
        }
        if(ordersize==0)
        {
            if(price-lasttradeprice>1*LIMITSTEP)
            {
                om->new_order(symbol,"SELL","OPEN",price-PRICESTEP,ORDERSZ);
                lasttradeprice=price;
                ordersize--;
            }
            if(price-lasttradeprice<-1*LIMITSTEP)
            {
                om->new_order(symbol,"BUY","OPEN",price+PRICESTEP,ORDERSZ);
                lasttradeprice=price;
                ordersize++;
            }
        }
        else if(ordersize>0)
        {
            if(price-lasttradeprice>1*LIMITSTEP)
            {
                om->new_order(symbol,"SELL","CLOSE",price-PRICESTEP,ORDERSZ);
                lasttradeprice=price;
                ordersize--;
            }
            if(price-lasttradeprice<-1*LIMITSTEP)
            {
                om->new_order(symbol,"BUY","OPEN",price+PRICESTEP,ORDERSZ);
                lasttradeprice=price;
                ordersize++;
            }
        }
        else if(ordersize<0)
        {
            if(price-lasttradeprice>1*LIMITSTEP)
            {
                om->new_order(symbol,"SELL","OPEN",price-PRICESTEP,ORDERSZ);
                lasttradeprice=price;
                ordersize--;
            }
            if(price-lasttradeprice<-1*LIMITSTEP)
            {
                om->new_order(symbol,"BUY","CLOSE",price+PRICESTEP,ORDERSZ);
                lasttradeprice=price;
                ordersize++;
            }
        }
    }
    if(symbol=="IF1503")
    {
        if(lasttradeprice_1==0)
        {
            lasttradeprice_1=price;
        }
        if(ordersize_1==0)
        {
            if(price-lasttradeprice_1>1*LIMITSTEP)
            {
                om->new_order(symbol,"BUY","OPEN",price+PRICESTEP,ORDERSZ);
                lasttradeprice_1=price;
                ordersize_1--;
            }
            if(price-lasttradeprice_1<-1*LIMITSTEP)
            {
                om->new_order(symbol,"SELL","OPEN",price-PRICESTEP,ORDERSZ);
                lasttradeprice_1=price;
                ordersize_1++;
            }
        }
        else if(ordersize_1>0)
        {
            if(price-lasttradeprice_1>1*LIMITSTEP)
            {
                om->new_order(symbol,"BUY","OPEN",price+PRICESTEP,ORDERSZ);
                lasttradeprice_1=price;
                ordersize_1--;
            }
            if(price-lasttradeprice_1<-1*LIMITSTEP)
            {
                om->new_order(symbol,"SELL","CLOSE",price-PRICESTEP,ORDERSZ);
                lasttradeprice_1=price;
                ordersize_1++;
            }
        }
        else if(ordersize_1<0)
        {
            if(price-lasttradeprice_1>1*LIMITSTEP)
            {
                om->new_order(symbol,"BUY","CLOSE",price+PRICESTEP,ORDERSZ);
                lasttradeprice_1=price;
                ordersize_1--;
            }
            if(price-lasttradeprice_1<-1*LIMITSTEP)
            {
                om->new_order(symbol,"SELL","OPEN",price-PRICESTEP,ORDERSZ);
                lasttradeprice_1=price;
                ordersize_1++;
            }
        }
    }
}
